#
# This is the user-interface definition of a Shiny web application. You can
# run the application by clicking 'Run App' above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
    verticalLayout(
        # Application title
        titlePanel("Pump it Up - Data Mining the Water Table"),
        
        # Sidebar with a slider input for number of bins
        tabsetPanel(
            tabPanel(
                "Association Rules",
                h3("Hyperparameters"),
                flowLayout(
                    sliderInput("sup",
                                "Support",
                                min = 0,
                                max = 1,
                                value = 0.01),
                    sliderInput("con",
                                "Confidence",
                                min = 0,
                                max = 1,
                                value = 0.5),
                    sliderInput("len",
                                "Minimum rule length",
                                min = 5,
                                max = 9,
                                value = 5)
                ),
                radioButtons("stat", 
                             "Pump status", 
                             choices = c("status_group=functional", 
                                         "status_group=functional needs repair", 
                                         "status_group=non functional")),
                h3("Top 3 rules"),
                verbatimTextOutput("arules")
            ),
            
            tabPanel(
                "Decision Tree",
                h3("Hyperparameter"),
                numericInput("cp", 
                             "Complexity parameter",
                             value = 0.01,
                             min = 0,
                             max = 0.1,
                             step = 0.01),
                verbatimTextOutput("dt"),
                h3("Predicting the pump status"),
                flowLayout(
                    selectInput("dt1", 
                                "Funder", 
                                choices = c("tasaf", "kkkt", "rwssp", "dwsp", "danida", "government of tanzania", "world vision", 
                                            "dhv", "norad", "world bank", "district council", "private individual", "hesawa", 
                                            "unicef", "other")),
                    numericInput("dt2",
                                 "GPS height",
                                 value = 100,
                                 min = 0),
                    selectInput("dt3",
                                "Installer",
                                choices = c("danida", "district council", "ces", "world vision", "central government", "government",
                                            "rwe", "danid", "commu", "hesawa", "dwe", "community", "kkkt", "tcrs", "other")),
                    numericInput("dt4",
                                 "Region code",
                                 value = 4,
                                 min = 1),
                    numericInput("dt5",
                                 "District code",
                                 value = 63,
                                 min = 0),
                    numericInput("dt6",
                                 "Population",
                                 value = 3000,
                                 min = 0),
                    selectInput("dt7",
                                "Extraction type",
                                choices = c("handpump", "rope pump", "motorpump", "gravity", "submersible", "wind-powered", "other")),
                    selectInput("dt8",
                                "Payment",
                                choices = c("never pay", "pay per bucket", "pay when scheme fails", "pay annually", "pay monthly",
                                            "other", "unknown")),
                    selectInput("dt9",
                                "Water quality",
                                choices = c("milky", "good", "salty", "colored", "fluoride", "unknown")),
                    selectInput("dt10",
                                "Water availability",
                                choices = c("enough", "insufficient", "dry", "seasonal", "unknown")),
                    numericInput("dt11",
                                 "Age of the pump",
                                 value = 22,
                                 min = 0)
                ),
                verbatimTextOutput("dt_test")
            ),
            
            tabPanel(
                "Random Forest Classifier",
                h3("Hyperparameter"),
                numericInput("mtry",
                             "Randomly selected predictors",
                             value = 2),
                verbatimTextOutput("rf"),
                h3("Predicting the pump status"),
                flowLayout(
                    selectInput("rf1", 
                                "Funder", 
                                choices = c("tasaf", "kkkt", "rwssp", "dwsp", "danida", "government of tanzania", "world vision", 
                                            "dhv", "norad", "world bank", "district council", "private individual", "hesawa", 
                                            "unicef", "other")),
                    numericInput("rf2",
                                 "GPS height",
                                 value = 100,
                                 min = 0),
                    selectInput("rf3",
                                "Installer",
                                choices = c("danida", "district council", "ces", "world vision", "central government", "government",
                                            "rwe", "danid", "commu", "hesawa", "dwe", "community", "kkkt", "tcrs", "other")),
                    numericInput("rf4",
                                 "Region code",
                                 value = 4,
                                 min = 1),
                    numericInput("rf5",
                                 "District code",
                                 value = 63,
                                 min = 0),
                    numericInput("rf6",
                                 "Population",
                                 value = 3000,
                                 min = 0),
                    selectInput("rf7",
                                "Extraction type",
                                choices = c("handpump", "rope pump", "motorpump", "gravity", "submersible", "wind-powered", "other")),
                    selectInput("rf8",
                                "Payment",
                                choices = c("never pay", "pay per bucket", "pay when scheme fails", "pay annually", "pay monthly",
                                            "other", "unknown")),
                    selectInput("rf9",
                                "Water quality",
                                choices = c("milky", "good", "salty", "colored", "fluoride", "unknown")),
                    selectInput("rf10",
                                "Water availability",
                                choices = c("enough", "insufficient", "dry", "seasonal", "unknown")),
                    numericInput("rf11",
                                 "Age of the pump",
                                 value = 22,
                                 min = 0)
                ),

            ),
            
            tabPanel(
                "Support Vector Machines with Radial Basis Function Kernel",
                h3("Hyperparameters"),
                flowLayout(
                    numericInput("sigma",
                                 "Sigma",
                                 value = 0.0988),
                    numericInput("c",
                                 "Cost",
                                 value = 1)
                ),

                h3("Predicting the pump status"),
                flowLayout(
                    selectInput("svm1", 
                                "Funder", 
                                choices = c("tasaf", "kkkt", "rwssp", "dwsp", "danida", "government of tanzania", "world vision", 
                                            "dhv", "norad", "world bank", "district council", "private individual", "hesawa", 
                                            "unicef", "other")),
                    numericInput("svm2",
                                 "GPS height",
                                 value = 100,
                                 min = 0),
                    selectInput("svm3",
                                "Installer",
                                choices = c("danida", "district council", "ces", "world vision", "central government", "government",
                                            "rwe", "danid", "commu", "hesawa", "dwe", "community", "kkkt", "tcrs", "other")),
                    numericInput("svm4",
                                 "Region code",
                                 value = 4,
                                 min = 1),
                    numericInput("svm5",
                                 "District code",
                                 value = 63,
                                 min = 0),
                    numericInput("svm6",
                                 "Population",
                                 value = 3000,
                                 min = 0),
                    selectInput("svm7",
                                "Extraction type",
                                choices = c("handpump", "rope pump", "motorpump", "gravity", "submersible", "wind-powered", "other")),
                    selectInput("svm8",
                                "Payment",
                                choices = c("never pay", "pay per bucket", "pay when scheme fails", "pay annually", "pay monthly",
                                            "other", "unknown")),
                    selectInput("svm9",
                                "Water quality",
                                choices = c("milky", "good", "salty", "colored", "fluoride", "unknown")),
                    selectInput("svm10",
                                "Water availability",
                                choices = c("enough", "insufficient", "dry", "seasonal", "unknown")),
                    numericInput("svm11",
                                 "Age of the pump",
                                 value = 22,
                                 min = 0)
                ),

            ),
            
            tabPanel(
                "eXtreme Gradient Boosting",
                h3("Hyperparameters"),
                flowLayout(
                    numericInput("nr",
                                 "Boosting iterations",
                                 value = 150),
                    numericInput("mdp",
                                 "Max tree depth",
                                 value = 3)
                ),

                h3("Predicting the pump status"),
                flowLayout(
                    selectInput("xgb1", 
                                "Funder", 
                                choices = c("tasaf", "kkkt", "rwssp", "dwsp", "danida", "government of tanzania", "world vision", 
                                            "dhv", "norad", "world bank", "district council", "private individual", "hesawa", 
                                            "unicef", "other")),
                    numericInput("xgb2",
                                 "GPS height",
                                 value = 100,
                                 min = 0),
                    selectInput("xgb3",
                                "Installer",
                                choices = c("danida", "district council", "ces", "world vision", "central government", "government",
                                            "rwe", "danid", "commu", "hesawa", "dwe", "community", "kkkt", "tcrs", "other")),
                    numericInput("xgb4",
                                 "Region code",
                                 value = 4,
                                 min = 1),
                    numericInput("xgb5",
                                 "District code",
                                 value = 63,
                                 min = 0),
                    numericInput("xgb6",
                                 "Population",
                                 value = 3000,
                                 min = 0),
                    selectInput("xgb7",
                                "Extraction type",
                                choices = c("handpump", "rope pump", "motorpump", "gravity", "submersible", "wind-powered", "other")),
                    selectInput("xgb8",
                                "Payment",
                                choices = c("never pay", "pay per bucket", "pay when scheme fails", "pay annually", "pay monthly",
                                            "other", "unknown")),
                    selectInput("xgb9",
                                "Water quality",
                                choices = c("milky", "good", "salty", "colored", "fluoride", "unknown")),
                    selectInput("xgb10",
                                "Water availability",
                                choices = c("enough", "insufficient", "dry", "seasonal", "unknown")),
                    numericInput("xgb11",
                                 "Age of the pump",
                                 value = 22,
                                 min = 0)
                ),

            )
        )
    )))
